Feature/display songs
Yrja/MusicPlayer pull request #1
Opened 2020-04-13 08:25 UTC by Yrja

2020-04-13 09:05 UTC, IvanGalitskiy requested changes

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/PlayerApplication.kt
> +
Useless line

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/dagger/AppModule.kt
> +
Useless line

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/dagger/MainActivityChildrenModule.kt
> +
Useless line

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/dagger/SongsModule.kt
> +    fun provideSongsRepository(songsDataSource: SongsDataSource): SongsRepository =
It can be Singleton, as you will use it in whole project

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +            val songsList = ArrayList<Song>()
Use songs instead of songsList

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +            val songUri = MediaStore.Audio.Media.EXTERNAL_CONTENT_URI
It is not songUri. songUri it is uri for specific song

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +            val songCursor = contentResolver.query(songUri, null, null, null, null)
songsCursor

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +                val albumName: Int = songCursor.getColumnIndex(MediaStore.Audio.Media.ALBUM)
Those fields are not value, please specify this in their names

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +                    val currentSongAlbumName: String = songCursor.getString(albumName)
Use the same naming style - or currentAlbumId, or currentSongTitle etc.

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +                    var songArtPath: String? = null
Art is not clear, use full name

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +    fun requireAndroidQAPI(songAlbumName: String): Bitmap? {
Incorrect method name

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +
Useless line

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +    override fun getSongs(): Single<List<Song>> {
Method is too big, please split this

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +    private fun apiLowerThanAndroidQ(currentSongAlbumId: Long): String? {
Incorrect method name

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +        val albumCursor = contentResolver.query(
albumsCursor

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +        val albumUri = MediaStore.Audio.Albums.EXTERNAL_CONTENT_URI
It is not albumUri

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +        val albumCursor: Cursor? = contentResolver.query(
albums

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +            val albumName: Int = cursor.getColumnIndex(MediaStore.Audio.Albums.ALBUM)
Those fields are not value, please specify this in their names

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +                        ex.printStackTrace()
remove this

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/SongsRepositoryImpl.kt
> +class SongsRepositoryImpl constructor(var contentResolver: SongsDataSource): SongsRepository {
Redundant constructor keyword

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/SongsRepositoryImpl.kt
> +        TODO("Not yet implemented")
Do not include unfinished code into PR, for this time leave this as it is

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/model/songs/SongsInteractorImpl.kt
> +class SongsInteractorImpl @Inject constructor( var repository:SongsRepository): SongsInteractor {
Redundant space

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/model/songs/SongsInteractorImpl.kt
> +class SongsInteractorImpl @Inject constructor( var repository:SongsRepository): SongsInteractor {
Use Ctrl+Alt+L here, a lot of bad formatting

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/MainActivity.kt
> +
too big space between code and fields, remove some blank lines

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/MainActivity.kt
> +        compositeDisposable.add(disposable)
Move this code to separate method

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/MainActivity.kt
> +                    supportFragmentManager.beginTransaction()
You can create some base method for navigation in base class or create separate class Router

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/MainActivity.kt
> +        }
replace on `compositeDisposable.clear()`

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongAdapter.kt
> +        private val songImage = itemView.findViewById<ImageView>(R.id.vSongImage)
Why not synthetics?

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongAdapter.kt
> +            Glide.with(context)
Don't use Glide inside you classes, it will be hard to remove this dependency in the future. Create Wrapper class and use it.

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +
Useless line

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/MainActivity.kt
> +            takeAudiosBinder.getPermissionResult(arrayListOf(Manifest.permission.READ_EXTERNAL_STORAGE))
requestPermission will be better

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/MainActivity.kt
> +                    Toast.makeText(this, "No permission granted", Toast.LENGTH_SHORT).show()
Not handled behavior in else block

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongAdapter.kt
> +
Redundant lines here and below

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +
Redundant line

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +    lateinit var androidFragmentInjector: DispatchingAndroidInjector<Any>
Maybe it is better to move this to BaseFragment class?

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +        presenter.attachView(this)
It will not work if user will tap on home button and will return back to application - view will be detached in this case

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +            "https://honestlywtf.com/wp-content/uploads/2019/05/driedflowers22.jpg"
Use real placeholder image

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +        val adapter = SongAdapter(songs)
Do not create adapter each time when you will provide list of songs. Create adapter once and use DiffUtils to display changes

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +    }
Not implemented behavior

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +
Redundant line

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +        requiredPermissions.addAll(permissions)
Redundant lines

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +         return   if (notGrantedPermissions.isNotEmpty()) {
redundant spaces

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +                    .filter { it.grantResults.isNotEmpty() && it.grantResults[0] == PackageManager.PERMISSION_GRANTED }
You should check result for all permissions, not only for first

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +                    }
Why you need this?

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +                    .ignoreElement()
You can use `ignoreElemnts()` instead of those two lines

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +            } else{
formatting issue

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +
Redundant line

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/presenter/BasePresenter.kt
> +        }
use `compositeDisposable.clear()` instead of this section

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/presenter/SongsPresenter.kt
> +interface SongsPresenter:BasePresenter<SongsView> {
Formatting issue

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/presenter/SongsPresenterImpl.kt
> +class SongsPresenterImpl @Inject constructor( var songsInteractor: SongsInteractor): SongsPresenter {
Not needed Inject and constructor keywords

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/presenter/SongsPresenterImpl.kt
> +class SongsPresenterImpl @Inject constructor( var songsInteractor: SongsInteractor): SongsPresenter {
Also formatting issue here

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/presenter/SongsPresenterImpl.kt
> +                .subscribeOn(Schedulers.io())
formatting issue

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/presenter/SongsPresenterImpl.kt
> +        view?.showLoading()
Move this to `doOnSubscribe` it will be more readable

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/presenter/SongsPresenterImpl.kt
> +
Redundant line

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/res/layout/song_item.xml
> +    android:layout_margin="5dp">
hardcoded margin, use dimens

2020-04-13 09:05 UTC, IvanGalitskiy commented on app/src/main/res/layout/song_item.xml
> +    android:layout_margin="5dp">
For all this file

2020-04-13 10:25 UTC, Yrja commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +                    }
If request is cancelled, the result arrays are empty.

2020-04-14 15:00 UTC, IvanGalitskiy requested changes

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/data/ContentResolverDSImpl.kt
> +class ContentResolverDSImpl constructor(var contentResolver: ContentResolver) : SongsDataSource {
Redundant word constructor

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/model/songs/SongsInteractorImpl.kt
> +class SongsInteractorImpl(private var repository: SongsRepository) :
val instead of var

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsDiffUtilCallback.kt
> +        return oldSong.songName == newSong.songName &&
Use simple == for old and new song comparation

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +    private lateinit var takeAudiosBinder: RequestPermissionsBinder
this field is not related to audio

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +    private lateinit var imageLoader: ImageLoader
provide this form dagger

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +    private lateinit var takeAudiosBinder: RequestPermissionsBinder
provide permissionsStream and takeAudiosBinder fields form dagger

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +    companion object {
Move companion object to the bottom

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/SongsFragment.kt
> +                error?.message ?: getString(R.string.uploading_songs_msg_error),
Better use localizedMessage instead of message

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/image_helper/ImageLoader.kt
> +
Redundant line

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/java/com/example/music/player/view/permission_helper/GetPermissionBinder.kt
> +                                throw Exception()
Move this to separate method

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/res/drawable/ic_folder.xml
> +</vector>
Unused resource, use android studio tool to remove unused resources

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/res/drawable/ic_folder_.xml
> +<vector android:height="24dp" android:viewportHeight="512"
Bad name of file

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/res/layout/song_item.xml
> +        android:layout_height="wrap_content">
Orientation is not specified

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/res/layout/song_item.xml
> +                tools:ignore="ContentDescription" />
Do not suppress this, provide content description

2020-04-14 15:00 UTC, IvanGalitskiy commented on app/src/main/res/layout/songs_fragment.xml
> +        android:progress="20"
It is not needed

2020-04-15 11:30 UTC, IvanGalitskiy approved these changes

2020-04-15 11:31 UTC, merged